services:
  structurizr:
    image: structurizr/structurizr
    command: local
    environment:
      STRUCTURIZR_AUTOREFRESHINTERVAL: 200
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/local/structurizr
    stdin_open: true
    tty: true
