add_subdirectory(libxe-cmake-checker-core)
add_subdirectory(libxe-cmake-checker-io)
add_subdirectory(libxe-cmake-checker-analysis)
add_subdirectory(libxe-cmake-checker-dsl)
add_subdirectory(libxe-cmake-checker-script)
add_subdirectory(libxe-cmake-checker-rule-engine)
add_subdirectory(libxe-cmake-checker-testing)
add_subdirectory(xe-cmake-checker)

if (XE_ENABLE_TESTING)
    add_subdirectory(libxe-cmake-checker-core-test)
    add_subdirectory(libxe-cmake-checker-io-test)
    add_subdirectory(libxe-cmake-checker-analysis-test)
    add_subdirectory(libxe-cmake-checker-dsl-test)
    add_subdirectory(libxe-cmake-checker-script-test)
    add_subdirectory(libxe-cmake-checker-rule-engine-test)
    add_subdirectory(xe-cmake-checker-test)
    add_subdirectory(xe-cmake-checker-e2e-test)
endif()