function(set_target_folder folder)
    foreach(target IN LISTS ARGN)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${folder}")
        else()
            message(WARNING "set_target_folder: '${target}' is not a target")
        endif()
    endforeach()
endfunction()
